### ISSUE TITLE
Documentation for Phase 1

### ISSUE THREAD

**Issue by xIvqn** [CodeURJC-DAW-2022-23/webapp9#11]
Add the required information in the practice statement to the README of the repository. This information includes screenshots of the screens and the corresponding navigation diagram. The original text is attached below for more information:

> Se añadirá a la información de la fase 0 en el README del repositorio la siguiente documentación:
> 
> - Capturas de las pantallas: Se incluirán capturas de pantalla de cada una de las páginas principales que hayan sido maquetadas. Se acompañarán con una breve descripción en cada una de ellas (un párrafo como mucho).
> - Diagrama de navegación: Para mostrar la navegación se creará un diagrama en el que se indicará desde qué página se puede navegar hasta otras páginas. Para ello, las páginas del diagrama pueden ser capturas de pantalla en miniatura de las maquetaciones que se hayan realizado. A continuación se muestra un ejemplo de diagrama de navegación:
>
> ![image](https://user-images.githubusercontent.com/72264031/218339437-e445e660-bf38-4a67-a3ed-25a698a9746c.png)

**Comment by LovetheFrogs** [comment]
Closed, added required documentation
