### ISSUE TITLE
Details View

### ISSUE THREAD

**Issue by AdayaUwU** [CodeURJC-DAW-2022-23/webapp9#147]
This issue includes:

- [x] Reviews handling
- [x] Access authorization handling (private itineraries)
- [x] Copy itinerary
- [x] Add place to itinerary
- [x] Delete place from itinerary
- [x] Download itinerary pdf
- [x] Item views update

Optional:
- [x] Check pdf filename

**Comment by xIvqn** [comment]
Closed with #151
