### ISSUE TITLE
Search results View

### ISSUE THREAD

**Issue by xIvqn** [CodeURJC-DAW-2022-23/webapp9#5]
Search results view for unregistered users:
![image](https://user-images.githubusercontent.com/72264031/217196803-18ec7ceb-fd90-4209-9a75-127aab1f654e.png)

Search results view for registered users:
![image](https://user-images.githubusercontent.com/72264031/217196824-e505fa0f-9315-4a2a-b5aa-f40f74b06928.png)

Search results view for administrators:
![image](https://user-images.githubusercontent.com/72264031/217196878-b3cb7216-2047-4384-a253-a478bb5b3887.png)

**Comment by AdayaUwU** [comment]
Pending style, review if the layout and components are correct
- [ ] @LovetheFrogs 
- [ ] @anna-trofimova 
- [ ] @xIvqn

**Comment by xIvqn** [comment]
Done in aa5a5ed5834c6b74206fa4f0536ee81d12765e91, 069331b90c90b57eab87fb1637676effcb476022, bb19d7d396b202886118444ac26a50981d80574b and bc0bcc6e72bea3f25b94399e7466e01318e998bc
