### ISSUE TITLE
Registered user functionality API REST

### ISSUE THREAD

**Issue by xIvqn** [CodeURJC-DAW-2022-23/webapp9#86]
Must implement:

- [x] Create new both public and private Itineraries.
- [x] Copy public Itineraries creating a private one for them.
- [x] Edit all owned Itineraries fields.
- [x] Edit their profile (including the profile picture).
- [x] Export Itineraries details to pdf.
- [x] Log in.

**Comment by LovetheFrogs** [comment]
At this point, left to implement editing an itinerary, editing an itinerary's image, exporting and coping (to private, owned itinerary)

**Comment by xIvqn** [comment]
Closed with #115 .
