### ISSUE TITLE
Change items' view in index

### ISSUE THREAD

**Issue by xIvqn** [CodeURJC-DAW-2022-23/webapp9#9]
Replace lists in index file by top 3 items for each categories and a "view more" button.

**Comment by AdayaUwU** [comment]
Pending style, review if the layout and components are correct
- [ ] @LovetheFrogs 
- [ ] @anna-trofimova 
- [ ] @xIvqn

**Comment by xIvqn** [comment]
Done in 826320fdfe03cdaed30df85f24a5c9ce2a798089
